In [10]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
import pickle

In [35]:
#Load the dataset

df=pd.read_csv('Churn_Modelling.csv')
df.head(5)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [36]:
df.drop(columns=['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [37]:
df.head(5)

CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [38]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [39]:
label_encoder=LabelEncoder()
df['Gender']=label_encoder.fit_transform(df['Gender'])
df['Gender'].unique()

array([0, 1])

In [40]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [41]:
onehot_encoder=OneHotEncoder()
encoded_geo=onehot_encoder.fit_transform(df[['Geography']])
encoded_geo

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [42]:
#to convert sparse matrix into arrays
encoded_geo.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [43]:
geo_df=pd.DataFrame(encoded_geo.toarray(),columns=onehot_encoder.get_feature_names_out(['Geography']))

In [44]:
geo_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [45]:
# combine all the columns
df=pd.concat([df.drop(columns=['Geography']),geo_df],axis=1)

In [46]:
df.head()

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [84]:
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder,file)

with open('one_hot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder,file)

In [49]:
df.head()

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [50]:
x=df.drop(columns=['Exited'],axis=1)
y=df['Exited']

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20,random_state=42)

scaler=StandardScaler()
scaler.fit_transform(xtrain)
scaler.transform(xtest)

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [51]:
xtrain

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
9254          686       1  ...                0.0              0.0
1561          632       1  ...                1.0              0.0
1670          559       1  ...                0.0              1.0
6087          561       0  ...                0.0              0.0
6669          517       1  ...                0.0              0.0
...           ...     ...  ...                ...              ...
5734          768       1  ...                0.0              0.0
5191          682       0  ...                0.0              0.0
5390          735       0  ...                0.0              0.0
860           667       1  ...                0.0              0.0
7270          697       1  ...                1.0              0.0

[8000 rows x 12 columns]

In [52]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

ANN Implementation

In [54]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [56]:
#Build model

model=Sequential([
    Dense(64,activation='relu',input_shape=(xtrain.shape[1],)), ##HL1
    Dense(32,activation='relu'),  ##HL2
    Dense(1,activation='sigmoid')  ## ouput layer
])

c:\ANN Project\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [57]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [60]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
tensorflow.keras.losses.BinaryCrossentropy()

In [61]:
# complie model

model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

In [63]:
# set up tensor board
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard


log_dir='logs/fit'+ datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [73]:
# set up early stopping

early_stopping_callbacks=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [74]:
# Trainig the model
history=model.fit(
    xtrain,ytrain,validation_data=(xtest,ytest),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callbacks]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7996 - loss: 0.5013 - val_accuracy: 0.8035 - val_loss: 0.4958
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7916 - loss: 0.5122 - val_accuracy: 0.8035 - val_loss: 0.4959
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5148 - val_accuracy: 0.8035 - val_loss: 0.4959
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8014 - loss: 0.4989 - val_accuracy: 0.8035 - val_loss: 0.4959
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8031 - loss: 0.4964 - val_accuracy: 0.8035 - val_loss: 0.4972
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8014 - loss: 0.4992 - val_accuracy: 0.8035 - val_loss: 0.4960
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8001 - loss: 0.5005 - val_accuracy: 0.8035 - val_loss: 0.4972
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7963 - loss: 0.5058 - val_accu

In [75]:
model.save('model.h5')

In [76]:
#load tensor board extension

%load_ext tensorboard

In [83]:
%tensorboard --logdir logs/fit20241010-120944

Reusing TensorBoard on port 6009 (pid 38552), started 0:00:10 ago. (Use '!kill 38552' to kill it.)